### ISSUE TITLE
Trying to recall a file/directory that already exists generates a runtime error

### ISSUE THREAD

**Issue by dvjones89** [dvjones89/sheldon#30]
### Steps To Reproduce:
Use `sheldon recall` to recall a directory that already exists on your host

### Expected Result:
You're informed that the directory already exists and are given the option to overwrite, if you so desire.

### Actual Result:
A runtime error is thrown in the console, for example:
```ruby
#<DestinationNotEmptyException: /home/pi/.oh-my-zsh/custom/plugins already exists.>
/home/pi/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/sheldon-6.0.9/lib/sheldon/brain.rb:48:in `recall'
/home/pi/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/sheldon-6.0.9/lib/sheldon/sheldon.rb:33:in `recall'
/home/pi/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/sheldon-6.0.9/bin/sheldon:73:in `block (2 levels) in recall'
/home/pi/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/sheldon-6.0.9/bin/sheldon:135:in `with_exception_handling'
/home/pi/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/sheldon-6.0.9/bin/sheldon:73:in `block in recall'
/home/pi/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/sheldon-6.0.9/bin/sheldon:71:in `each'
/home/pi/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/sheldon-6.0.9/bin/sheldon:71:in `recall'
```

**Comment by dvjones89** [comment]
Fixed in 0e8dfca4e96de735622d1a814e928cabfcef6a9f
